global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-enterprise-accelerator-cjis
  regions:
    - eu-west-1
    - eu-west-2
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
tests:
  defaults:
    parameter_input: defaults.json
    template_file: main.template
